export const SEARCH_PRODUCTS_START = "SEARCH_PRODUCTS_START";
export const SEARCH_PRODUCTS_ERROR = "SEARCH_PRODUCTS_ERROR";
export const SEARCH_PRODUCTS_COMPLETE = "SEARCH_PRODUCTS_COMPLETE";

export const SEARCH_PRODUCT_BY_ID_START = "SEARCH_PRODUCT_BY_ID_START";
export const SEARCH_PRODUCT_BY_ID_ERROR = "SEARCH_PRODUCT_BY_ID_ERROR";
export const SEARCH_PRODUCT_BY_ID_COMPLETE = "SEARCH_PRODUCT_BY_ID_COMPLETE";
